### ISSUE TITLE
Add Features like pausing and resuming.

### ISSUE THREAD

**Issue by gwashark** [jjophoven/Free-Roblox-Studio-Video#2]
You should Add a feature to pause and resume. If you can do so.

Otherwise, this is great as I am trying to play Youtube Videos in Roblox.

**Comment by jjophoven** [comment]
Will add this soon.

**Comment by gwashark** [comment]
Nice. I was going to ask for audio as well but that may be beyond we can do.

**Comment by jjophoven** [comment]
I could add just a audio file that plays along with the video.

**Comment by jjophoven** [comment]
@gwashark 

Pausing has been implemented with f890bf6413c15b87f34419e2d8a3c5607605549c
