### ISSUE TITLE
How to work this

### ISSUE THREAD

**Issue by gwashark** [jjophoven/Free-Roblox-Studio-Video#4]
Sorry to bring up another issue, but I can't install LUASprites. I am using Windows 11 and Python 3. I tried multipule ways but they all failed.

**Comment by jjophoven** [comment]
Did you get an error? Did it not recognize pip? Does the command line recognize `python` keyword?

**Comment by gwashark** [comment]
Solved in Discord

**Comment by jjophoven** [comment]
Solved By Limiting Version to 3.11 Python
