### ISSUE TITLE
Not really a issue.

### ISSUE THREAD

**Issue by yeenrux** [jjophoven/Free-Roblox-Studio-Video#5]
I don't understand where to put the made Roblox scripts. The code doesn't make any sense with what the tutorial is. I would like a video explaining how this works or detailed instructions.

Thank you.

Questions:

1: Does the video need to be in frames as a png instead of a single mp4 video?
2. What do I do with the "(video name).luau" file?

**Comment by gwashark** [comment]
I made a script where it is combined into one. It has all the configurations. I’ll make a PR so that it won’t be confusing.

**Comment by coltenthefirst** [comment]
@gwashark Thank you. Could you provide a link?

**Comment by coltenthefirst** [comment]
oops

**Comment by Py-mon** [comment]
The video does need to be in frames.

**Comment by Py-mon** [comment]
With the file generated you copy it into a module script in Roblox Studio. Then you can play the video by requiring it.

**Comment by Py-mon** [comment]
Put it underneath the Videos Module script
